name: Auto-Merge
on:
  pull_request_target:
    types:
      - labeled

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
    - uses: alexwilson/enable-github-automerge-action@c639c60a428a35aea587f0163bcb8d0ed2097538  # 1.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
