name: Sync EIPs Repository
on:
    schedule:
      - cron: "*/5 * * * *" # Every 5 minutes
    workflow_dispatch:
    pull_request_target:
        types:
          - opened
          - reopened
          - synchronize

jobs:
    submodule-sync:
        name: Submodule Sync
        runs-on: ubuntu-latest
        steps:
          - name: Submodule Sync
            uses: mheap/submodule-sync-action@96b11741d429d96ec3a6460b7e42d7528e09d6bb # v1.3.1
            if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
            with:
                path: EIPs
                ref: master
                pr_branch: automated-submodule-update
                target_branch: main
        
          - name: Debug
            if: github.event_name == 'pull_request_target'
            run: |
              echo "${{ github.ref }}"
              echo "${{ github.head_ref }}"
              echo "${{ github.event.pull_request.user.login }}"

          - name: Submodule Auto Merge
            uses: alexwilson/enable-github-automerge-action@c639c60a428a35aea587f0163bcb8d0ed2097538  # 1.0.0
            if: github.event_name == 'pull_request_target' && github.ref == 'refs/heads/automated-submodule-update'
            with:
                github-token: "${{ secrets.GITHUB_TOKEN }}"
                
