permissions:
  contents: write
  pull-requests: write
name: Sync EIPs Repository
on:
    schedule:
      - cron: "*/5 * * * *" # Every 5 minutes
    workflow_dispatch:
    pull_request_target:
        types:
          - opened
          - reopened
          - synchronize

jobs:
    submodule-sync:
        name: Submodule Sync
        runs-on: ubuntu-latest
        steps:
          - name: Fetch JWT
            id: fetch_jwt
            uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
            with:
              app_id: ${{ secrets.SUBMODULE_UPDATE_APP_ID }}
              private_key: ${{ secrets.SUBMODULE_UPDATE_PRIVATE_KEY }}
        
          - name: EIPs Submodule Sync
            uses: mheap/submodule-sync-action@a06903a4e38f042f6f52cc88d184ec1c930ee12d # v1.4.1
            if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
            with:
                token: "${{ steps.fetch_jwt.outputs.token }}"
                path: EIPs
                ref: master
                pr_branch: eips-automated-submodule-update
                target_branch: main

          - name: EIPs Submodule Auto Merge
            uses: alexwilson/enable-github-automerge-action@56e3117d1ae1540309dc8f7a9f2825bc3c5f06ff # 2.0.0
            if: github.event_name == 'pull_request_target' && github.head_ref == 'eips-automated-submodule-update' && github.event.pull_request.user.login == 'submodule-update[bot]'
            with:
                github-token: "${{ steps.fetch_jwt.outputs.token }}"
        
          - name: ERCs Submodule Sync
            uses: mheap/submodule-sync-action@a06903a4e38f042f6f52cc88d184ec1c930ee12d # v1.4.1
            if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
            with:
                token: "${{ steps.fetch_jwt.outputs.token }}"
                path: ERCs
                ref: master
                pr_branch: ercs-automated-submodule-update
                target_branch: main

          - name: ERCs Submodule Auto Merge
            uses: alexwilson/enable-github-automerge-action@56e3117d1ae1540309dc8f7a9f2825bc3c5f06ff # 2.0.0
            if: github.event_name == 'pull_request_target' && github.head_ref == 'ercs-automated-submodule-update' && github.event.pull_request.user.login == 'submodule-update[bot]'
            with:
                github-token: "${{ steps.fetch_jwt.outputs.token }}"
                
